package core.jsqlAss;

public interface ValidationConstants {

	public static final String SELECT_CLAUSE ="SELECT 1 FROM " ;
	public static final String WHERE_CLAUSE = "WHERE" ;
	public static final String AND = " AND " ;
	public static final String EQUAL = "=" ;
	public static final String SPACE = " " ;
	public static final String SCOLON = "'" ;
	public static final String SELECT ="SELECT";
	public static final String FROM = "FROM" ;
	public static final String COMMA = " , " ;
	public static final String IN ="IN" ;
	public static final String EBRA =" ) " ;
	public static final String SBRA =" ( " ;
	public static final String COMMIT = "COMMIT";
	public static final String MERGE ="MERGE" ;
	public static final String ALTER ="ALTER" ;
	public static final String TABLE = "TABLE" ;
	public static final int    DROP = 1 ;
	public static final int    ADD = 2 ;
	public static final int    MODIFY =3 ;
	public static final String    DROPE_ACTION = "DROP" ;
	public static final String    ALTER_ADD = "ADD" ;
	public static final String    ALTER_MODIFY ="MODIFY" ;
	public static final String STATEMENT_END = ";";
	public static final String ALL_TABLE = " ALL_TAB_COLUMNS ";
	public static final String ALTER_COL_NAME_CONJUCTION = "," ;
	public static final String SEC_COMMA = "," ;
	public static final String COLUMN = "COLUMN_NAME IN " ;
	public static final String TABLE_NAME = "TABLE_NAME " ;
	public static final String DROP_COLUMN ="COLUMN" ;
	public static final String ALTER_VAL_SQL = SELECT_CLAUSE + ALL_TABLE + WHERE_CLAUSE +SPACE+ COLUMN +SBRA ;
	public static final String RENAME = "RENAME";
	public static final String RENAME_CONJUCTION = "TO" ;
	public static final int	   SEC_IND =1 ;
	public static final int	   FST_IND =0 ;
	public static final String ALL_TAB = "ALL_TAB" ;
	public static final String MERGE_ON = " ON " ;
	public static final String MERGE_WHEN = "WHEN";
	public static final String MERGE_USING = "USING";
	public static final String MERGE_INTO = "MERGE INTO";
	public static final String INTO = "INTO ";
	public static final String ALIAS_DELIMETER = ".";
	//public static final String SEQUENCE_VAL_SQL = "SELECT <SEQ NAME>.NextVal FROM DUAL" ;
	public static final String SEQUENCE_VAL_SQL = "SELECT 1 FROM USER_SEQUENCES WHERE SEQUENCE_NAME ='<SEQ NAME>'" ;
	public static final String SEQUENCE = "SEQUENCE" ;
	public static final String INCREMENT = "INCREMENT" ;
	public static final String SEQ_NAME = "<SEQ NAME>" ;
	public static final String CREATE = "CREATE" ;
	public static final String DELETE = "DELETE" ;
	public static enum MISCELLANEOUS {GRANT,CREATE_INDEX,DELETE_INDEX,CREATE_VIEW,DROP_VIEW,CREATE_SYNONYM,DROP_SYNONYM} ;
	public static final String GRANT = "GRANT" ;
	public static final String TO = " TO " ;
	public static final String USER = "USER";
	public static final String GRANT_ACCESS = "GRANT_ACCESS";
	public static final String INDEX = " INDEX " ;
	public static final String INDEX_NAME = "INDEX_NAME";
	public static final String INDEX_COL_NAME = "INDEX_COL_NAME";
	public static final String INDX_EBRA =")" ;
	public static final String INDX_SBRA ="\\(" ;
	public static final String INDEX_REVESRE = "REVERSE";
	public static final String INDEX_NOREVESRE = "NOREVERSE";
	public static final String VIEW = " VIEW " ;
	public static final String AS=" AS ";
	public static final String VIEW_NAME = "VIEW_NAME";
	public static final String SYNONYM = "SYNONYM";
	public static final String SYNONYM_NAME = "SYNONYM_NAME";
	public static final String ACTION="ACTION";
	public static final String SEMI_COLON= " ; ";
	public static final String SET_PREFIX ="%SET_";
	public static final String REPLACE_IDENTIFIER = "%";
	public static final String SYNONYM_VAL_SQL = "SELECT 1 FROM ALL_SYNONYMS WHERE SYNONYM_NAME = '%SET_SYNONYM_NAME%'";
	public static final String VIEW_VAL_SQL = "SELECT 1 FROM ALL_VIEWS WHERE VIEW_NAME ='%SET_VIEW_NAME%'";
	public static final String CR_INDEX_VAL_SQL ="SELECT 1 FROM DBA_IND_COLUMNS WHERE TABLE_NAME ='%SET_TABLE_NAME%' AND INDEX_NAME ='%SET_INDEX_NAME%';";
	public static final String DE_INDEX_VAL_SQL ="SELECT 1 FROM DBA_IND_COLUMNS WHERE INDEX_NAME ='%SET_INDEX_NAME%';";
	public static final String GRANT_VAL_SQL = "SELECT 1 FROM DBA_TAB_PRIVS WHERE TABLE_NAME = '%SET_TABLE_NAME%';";
}
